name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose Installation
        run: docker-compose --version

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 30

      - name: Check Docker Logs for Services
        run: docker-compose logs

      - name: Run Integration Tests
        run: python3 test_user_service.py

      - name: Check Docker Logs after Tests
        run: docker-compose logs

      - name: Shut down Docker Compose
        run: docker-compose down
